// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogIconLibrary: typeof import('./../src/components/DialogIconLibrary/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MarsColorPicker: typeof import('./../src/components/marsUI/mars-color-picker/index.vue')['default']
    MarsInput: typeof import('./../src/components/marsUI/mars-input/index.vue')['default']
    MarsInputNumber: typeof import('./../src/components/marsUI/mars-input-number/index.vue')['default']
    MarsSelect: typeof import('./../src/components/marsUI/mars-select/index.vue')['default']
    MarsSelectV2: typeof import('./../src/components/marsUI/mars-select-v2/index.vue')['default']
    MarsSlider: typeof import('./../src/components/marsUI/mars-slider/index.vue')['default']
    MarsSwitch: typeof import('./../src/components/marsUI/mars-switch/index.vue')['default']
    MarsTextarea: typeof import('./../src/components/marsUI/mars-textarea/index.vue')['default']
    MarsUpload: typeof import('./../src/components/marsUI/mars-upload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  }
}
